FROM tensorflow/tensorflow:1.15.5-py3

ENV LANG=C.UTF-8
COPY ./container-bashrc /root/.bashrc

RUN mkdir /gpt-2
WORKDIR /gpt-2

# ADD . /gpt-2

COPY ./requirements.txt /gpt-2/requirements.txt
COPY ./download_model.py /gpt-2/download_model.py

RUN pip3 install -r requirements.txt

# RUN python3 download_model.py 124M
# RUN python3 download_model.py 355M
# RUN python3 download_model.py 774M
# RUN python3 download_model.py 1558M
